config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "home#index"

  post '/transference', to: 'accounts#transference' 

  resources :accounts
  resources :account_transactions
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/account.rb
class Account < ApplicationRecord
  
  belongs_to :user
  has_many :account_transactions, dependent: :destroy

  #Validations 
  validates_presence_of :user_id, :account_number, :bk_branch, :bk_number, :balance
  validates :user, presence: true

  validates :balance, numericality: { greater_than_or_equal_to: 0, message: 'Valor deve ser maior do que zero.', less_than: BigDecimal(10**3) },
    format: { with: /\A\d{1,3}(\.\d{1,2})?\z/ }

  def debits
    AccountTransaction.where(account_id: id, tr_type: 'D').sum(:amount)
  end

  def credits
    AccountTransaction.where(account_id: id, tr_type: 'C').sum(:amount) 
  end

  def account_balance
    b = self[:balance] - debits + credits
  end

  def prev_balance(date, app_id)
    debits =  AccountAppointment.where(:account_id => id, :tr_type => 'D').where('account_transactions.date <= ?', date).where('account_transactions.id <?', app_id).order(created_at: :desc, deb_cre: :desc).sum(:amount)
    credits =  AccountAppointment.where(:account_id => id, :tr_type => 'C').where('account_transactions.date <= ?', date).where('account_transactions.id <?', app_id).order(created_at: :desc, deb_cre: :desc).sum(:amount)
    result = balance - debits + credits
  end
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :account

  #Validations
  validates_presence_of :account_id, :tr_type, :amount

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts
end

app/controllers/account_transactions_controller.rb
class AccountTransactionsController < ApplicationController

  before_action :check_active, only: [:show, :edit, :update, :destroy]


  def index
    if (params[:start_date].present? && params[:end_date].present?)
      @account_filter = AccountTransaction.where(created_at: [params[:start_date].to_date..params[:end_date].to_date], account_id: params[:origin_account_id])
      #@account_filter = AccountTransaction.all 
    else  
      redirect_to account_path(params[:origin_account_id].to_i), notice: 'Por favor, defina as datas de início e fim.'
    end
  end
  
  def new
    @account_transaction = AccountTransaction.new 
  end

  def create
    @account_transaction = AccountTransaction.new(account_transaction_params)
    if @account_transaction.save
      redirect_to account_transactions_path, notice: 'Lançamento realizado!'
    else
      flash[:alert] = @account_transaction.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @account_transaction = AccountTransaction.find(params[:id])
  end

  def edit
  end

  def update
    @account_transaction = AccountTransaction.find(params[:id])
    if @account_transaction.update(account_transaction_params)
      redirect_to account_transaction_path(@account_transaction), notice: "A transação foi realizada!"
    else
      flash[:alert] = @account.errors.full_messages.join(', ')
      render :edit
    end 
  end 

  private 
  def account_transaction_params 
    params.require(:account_transaction).permit(:date, :doc_ref, :tr_type, :description, :amount, :account_id, :origin_account_id, :start_date, :end_date)
  end
  
  def check_active
    redirect_to accounts_path, alert: 'Por favor, escolha uma conta ativa.' unless params[:account_active] == "true"
  end

end

app/controllers/accounts_controller.rb
require 'util/appoints'

class AccountsController < ApplicationController
  

  def index
    @accounts = Account.where(user_id: current_user.id ) #Only the current user's accounts listed    
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.user_id = current_user.id
    if @account.save
      redirect_to account_path(@account), notice: "A conta foi criada!"
    else
      flash[:alert] = @account.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @account = Account.find(params[:id])
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to account_path(@account), notice: "A conta foi atualizada!"
    else
      flash[:alert] = @account.errors.full_messages.join(', ')
      render :edit
    end 
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to account_index_path
  end

  def transference 
    @conta_dest     = Account.find(params[:dest_account_id])
    @aconta_origem  = Account.find(params[:origin_account_id])
    saldo_origem = @aconta_origem.account_balance
    value_debt = params[:balance].to_d
      
    if (value_debt > 0)
      if (value_debt <= saldo_origem)
        msg = Appoints.call(params[:origin_account_id],params[:dest_account_id], value_debt)
        redirect_to accounts_path, notice: msg
      else
        flash.now[ :alert ] = 'Saldo indisponível para esta operação!'
        render :show
      end
    end
  end

  private 
  def account_params
    params.require(:account).permit(:id, :account_active, :account_number, :bk_branch, :bk_number, :details, :balance, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/util/appoints.rb
class Appoints

	def self.call(origin_account_id, dest_account_id, amount_debt)

    account = Account.find(origin_account_id) 

    if account
      tax_value = tax_value(amount_debt)
      if ((account.account_balance - tax_value - amount_debt) >= 0)
        # Atomicity Control
        AccountTransaction.transaction do
          # Creating debit transfer
          @lancto_origem = AccountTransaction.create(account_id: origin_account_id,
                                          date: Date.current, description: 'Debitado para transferência', tr_type: 'D', amount: amount_debt , doc_ref: "Conta: #{dest_account_id}" )
          # Tax Debt
          @lancto_origem = AccountTransaction.create(account_id: origin_account_id,
                                                     date: Date.current, description: 'Taxa referente à transferência', tr_type: 'D', amount: tax_value )
          # Crediting the amount in the destiny Account
          @lancto_destino = AccountTransaction.create(account_id: dest_account_id,
                                           date: Date.current, description: 'Transferência', tr_type: 'C', amount: amount_debt, doc_ref: "Transf. da Conta: #{origin_account_id}"  )
          msg = 'Transferência realizada com Sucesso!'
        end
      else
        msg = "Saldo insuficiente descontado o valor da TAXA de , operação não realizada"
      end
    else
      msg = "Conta ORIGEM - Cód. #{origin_account_id} não encontrada!"
    end
    return msg
  end

  #Apllies the taxes on transferences
	def self.tax_value(value_debt)
   
    date_transf = Time.current

    week_day = date_transf.wday # onde 0 é domingo
    hour = date_transf.hour

    normal_day = *(1..5) # Segunda a Sexta
    if normal_day.include?(week_day) and (hour >= 9 and hour <= 18)
      tax = 5
    else
      tax = 7
    end

    if (value_debt > 1000) # Acima de 1000 , adicional de 10 reais
      tax += 10
    end

    return tax
  end

end

app/helpers/account_transactions_helper.rb
module AccountTransactionsHelper
  
  def dep_or_saq (tr_type)
    if tr_type == 'C'
     'Depósito'
    else 
    	'Saque'
    end 
	end	
end

app/helpers/accounts_helper.rb
module AccountsHelper
  
  def check_active (account)
    if account.account_active?
      'Conta ativa'
    else 
      'Conta inativa'
    end  
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
			when :notice then "alert alert-info"
			when :success then "alert alert-success"
			when :error then "alert alert-error"
			when :alert then "alert alert-error"
		end
	end    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/account_transactions/_form.html.erb
<p>Data: <%= l Time.now, format: "%d/%m/%Y" %></p>

<%= form_for(@account_transaction) do |f| %>
<div class="card">
  <div class="card-body">
    <%= f.hidden_field :account_id , value: params[:account_id] %>
    <%= f.hidden_field :tr_type, value: params[:tr_type] %>
    
		<div class='mb-3'> 
			<%=f. label 'Documento de referencia' %>    
			<%= f.text_field :doc_ref, { class: 'form-control', placeholder: 'Algum código ou referência que deseja informar' } %>
		</div>

		<div class='mb-3'>   
				<%=f. label 'Descrição' %>  
			<%= f.text_field :description, { class: 'form-control', placeholder: 'Descrição da transação' } %>
		</div>

		<div class='mb-3'>
			<%=f. label 'Quantia' %>   
			<%= f.number_field :amount, min: 0.01, step: 0.01, class: 'form-control' %>
		</div>		

   	<%= f.submit 'Realizar transação', class: 'btn btn-success', data: {confirm: 'Tem certeza?'} %>
   	<%= link_to 'Cancelar',accounts_path, class: 'btn btn-primary' %>
  </div>
</div>
<% end %>

app/views/account_transactions/edit.html.erb
<h1>AccountTransactions#edit</h1>
<p>Find me in app/views/account_transactions/edit.html.erb</p>

app/views/account_transactions/index.html.erb
<p>Find me in app/views/account_transactions/index.html.erb</p>

<p>Perído entre: <%= params[:start_date] %> e <%= params[:end_date] %></p>

<table>
  <tbody>
    <% @account_filter.each do |t| %>
      <tr>
        <td>Data <%= l t.created_at, format: "%d/%m/%Y" %> - </td>
        <td>Valor <%= number_to_currency t.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/account_transactions/new.html.erb
<h4><%= dep_or_saq(params[:tr_type]) %></h4><!--this is a helper -->
 
<% if (params.has_key?(:account)) %>
  <p>Conta: <%= params[:account]%> </p>
<%end%>

<%= render 'form'%>

app/views/account_transactions/show.html.erb
<h1>AccountTransactions#show</h1>
<p>Find me in app/views/account_transactions/show.html.erb</p>

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
<div class="card">
  <div class="card-body">
    
		<div class="mb-3">
			<%= f.label 'Conta ativa', { class: "form-label"} %>
			<%= f.check_box :account_active%>
		</div>

		<div class="mb-3">     
			<%= f.text_field :bk_branch, { class: "form-control", placeholder: "Agência" } %>
		</div>

		<div class="mb-3">   
			<%= f.text_field :bk_number, { class: "form-control", placeholder: "Número do banco" } %>
		</div>

		<div class="mb-3">   
			<%= f.text_field :account_number, { class: "form-control", placeholder: "Número da conta" } %>
		</div>	

		<div class="mb-3">
			<%= f.label 'Depósito inicial', { class: "form-label"} %>
			<%= f.number_field :balance, min: 0.00, step: 0.01, class: "form-control" %>
		</div>

		<div class="mb-3">      
			<%= f.text_area :details, { class: "form-control", placeholder: "Detalhes" } %>
		</div>

    <%= f.submit "Criar", class: "btn btn-primary" %>

  </div>
</div>
<% end %>

app/views/accounts/_form_filter.html.erb
<%= form_tag(account_transactions_path, :method => "get") do %>
	<div class="row">
		<%= hidden_field_tag 'origin_account_id', @account.id %>
		<div class="col-auto">				
      <%= text_field_tag 'start_date', params[:start_date], placeholder: "Data início", class: 'form-control' %>
		</div>
		<div class="col-auto">		
			 <%= text_field_tag 'end_date', params[:end_date], placeholder: "Data fim", class: 'form-control' %>
		</div>
		<div class="col-auto">
			<%= submit_tag "Filtrar", class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/accounts/_form_transf.html.erb
<%= form_tag("/transference", :method => "post") do %>
	<div class="row">
		<%= hidden_field_tag 'origin_account_id', @account.id %>
		<div class="col-auto">				
			<%= select_tag 'dest_account_id', options_for_select(Account.where.not(account_number: @account.account_number).collect{ |c| [c.account_number, c.id]}), class: "form-select" %>
		</div>
		<div class="col-auto">		
			<%= number_field_tag 'balance', nil, step: 0.01, min: 0.01, class: 'form-control' %>
		</div>
		<div class="col-auto">
			<%= submit_tag "Transferir", class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/accounts/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Data</th>
      <th scope="col">Tipo</th>
      <th scope="col">Valor</th>
      <th scope="col">Descrição</th>
			<th scope="col">Conta</th>
    </tr>
  </thead>

	<tbody>    
		<% @account.account_transactions.each do |t| %>
			<tr>
				<th scope="row"><%= l t.created_at, format: "%d/%m/%Y"%></td>
				<td><%= t.tr_type %></td>
				<td><%= number_to_currency t.amount %></td>
				<td><%= t.description %></td>
				<td><%= t.doc_ref %></td>
			</tr>
		<% end %>
  </tbody>
</table>

app/views/accounts/edit.html.erb
<h3>Editar informações da conta</h3>

<%= render 'form' %>

app/views/accounts/index.html.erb
<h3>Suas contas</h3>

<%= link_to 'Cadastrar conta', new_account_path %>
<p>Seja bemvindo(a), <%= current_user.email %>! Essas são as suas contas:</p>


<% @accounts.each do |account| %>
	<p><%= link_to account.account_number, 
		account_path(account), class: 'link' %> 
		- Status: <%= check_active(account) %> 
		- Data criação: <%= l account.created_at, format: "%d/%m/%Y" %> 
		- Detalhes: <%= account.details %> 
	</p>	
<% end %>

app/views/accounts/new.html.erb
<h3>Cadastrar conta</h3>

<%= render 'form' %>

app/views/accounts/show.html.erb
<div class="row">
  <div class="col-lg-3 col-6">
    <div class="small-box bg-info">
      <div class="inner">
        <h3><%= number_to_currency @account.account_balance %></h3><!-- number_to_currency is a i18n helper method -->
        <p>Saldo atual</p>
      </div>
      <div class="icon">
        <i class="ion ion-bag"></i>
      </div>
      <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <div class="small-box bg-success">
      <div class="inner">
        <h3><%= number_to_currency @account.credits %></h3>
        <p>Total dos créditos</p>
      </div>
      <div class="icon">
        <i class="ion ion-stats-bars"></i>
      </div>
      <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <div class="small-box bg-warning">
      <div class="inner">
        <h3><%= number_to_currency @account.balance %></h3>
        <p>Depósito de abertura da conta</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <div class="col-lg-3 col-6">
    <div class="small-box bg-danger">
      <div class="inner">
        <h3><%= number_to_currency @account.debits %></h3>
        <p>Total dos débitos</p>
      </div>
      <div class="icon">
        <i class="ion ion-pie-graph"></i>
      </div>
      <a href="#" class="small-box-footer">Mais informações <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
</div>

<div class="card text-white bg-dark mb-3">
  <div class="card-header">
		<p>Agência: <%= @account.bk_branch %> - Conta número: <%= @account.account_number %> - Transferir para:</p>
		<%= render 'form_transf' %>
	</div>
    <div class="card-header">
		<%= render 'form_filter' %>
	</div>
</div>

<div class="card text-dark bg-light mb-3">
  <div class="card-header"><i class="fa fa-exchange" aria-hidden="true"></i>  Suas movimentações</div>
  <div class="card-body">
    <%= render 'table' %>
  </div>
</div>

<!-- Sending the accounts id to transactions -->
<%= link_to 'Depósito', new_account_transaction_path(account_id: @account.id, tr_type: 'C', account_active: @account.account_active), class: 'btn btn-success' %>
<%= link_to 'Saque', new_account_transaction_path(account_id: @account.id, tr_type: 'D', account_active: @account.account_active), class: 'btn btn-warning' %>
<%= link_to 'Voltar', accounts_path, class: 'btn btn-primary'%>

app/views/base/_control_sidebar.html.erb
  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
    <div class="p-3">
      <!-- Content of the sidebar goes here -->
    </div>
  </aside>
  <!-- /.control-sidebar -->

app/views/base/_footer.html.erb
<footer class="main-footer">
  <strong>Nobe-Bank:</strong> O banco digital 
  <div class="float-right d-none d-sm-inline-block">
    <b>e-mail:</b> teste@nobe.com.br / <b>ramal: </b>1852
  </div>
</footer>s

app/views/base/_header.html.erb
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Help
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">FAQ</a>
          <a class="dropdown-item" href="#">Support</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Contact</a>
        </div>
      </li>
    </ul>

    <!-- SEARCH FORM 
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    -->

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu 
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li> -->
      
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

app/views/base/_sidebar.html.erb
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <%= link_to root_path, class: "brand-link" do %> 
      <img src="https://cdn-icons-png.flaticon.com/512/438/438526.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
      style="opacity: .8">
      <span class="brand-text font-weight-light">Nobe-Bank</span>
    <% end %>           

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="https://avatars.githubusercontent.com/u/289846?v=4" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block"><%= current_user.email.truncate 23 if user_signed_in? %></a><!-- truncate shows only the 23 first characters -->
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu">
          <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Starter Pages
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Active Page</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Inactive Page</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Simple Link
                <span class="right badge badge-danger">New</span>
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <h4>Seja bemvindo, <%= current_user.email %>!</h4>
    <%= link_to "Sign out", destroy_user_session_path %>
    <p>Seu código de cliente é: <%= current_user.id %></p>
<% else %>
    <h4>Desculpe, você não está logado ainda </h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Nobe - Bank </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-scrollbar-auto-hide="n" class="hold-transition sidebar-mini layout-fixed">
    <% if user_signed_in? %>
    <div class="wrapper">
      <!--This code prints flash messages -->
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>

      <%= render "base/header" %>
      <%= render "base/sidebar" %>

      <div class="content-wrapper">
        <div class="content-header">
          <div class="container-fluid">
            <div class="row mb-2">
              <div class="col-sm-6">                
              </div><!-- /.col -->
              <!--
              <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                  <li class="breadcrumb-item"><a href="#">Home</a></li>
                  <li class="breadcrumb-item active">Starter Page</li>
                </ol>
              </div>-->
            </div><!-- /.row -->
          </div><!-- /.container-fluid -->
        </div>

        <div class="content container-fluid">
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
      </div>

      <%= render "base/footer" %>
      <%= render "base/control_sidebar" %>
    <div>
    <% else %>
      <%= render template: "devise/sessions/new" %>
    <% end %>
  </body>
</html>